name: hanyang_robot
channels:
  - conda-forge
  - robostack-staging
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit  # 서버 GPU 가속을 위해 추가
  - ros-humble-desktop
  - ros-humble-ros-gz-bridge
  - ros-humble-rclpy
  - gymnasium
  - aiohttp
  - numpy
  - matplotlib
  - pyyaml
  - opencv
  - cmake
  - ninja
  - pkg-config
  - pip
  - pip:
      - setuptools==70.0.0  # 가끔 최신버전 충돌 방지
variables:
  GZ_SIM_RESOURCE_PATH: ~/Autonomous_car_gz_ros_ddpg/models